# Generated by Django 5.0.6 on 2024-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
